bump rubyzip to 1.3.0
errors when running rspec:

An error occurred while loading ./spec/controllers/populations_controller_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
  undefined method `validate_entry_sizes=' for Zip:Module
# ./config/application.rb:18:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/controllers/populations_controller_spec.rb:1:in `require'
# ./spec/controllers/populations_controller_spec.rb:1:in `<top (required)>'